org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false

minecraft_version=1.21.1
mod_id=playercollars
mod_name=Leashable Collars
mod_license=MIT
mod_version=1.0.5
mod_group_id=com.dipilodopilasaurus
mod_authors=Dipilodopilasaurus
mod_description=An unofficial NeoForge 1.21.1 port of jlortiz0's Leashable Collars.
neo_version=21.1.228
moddevgradle_version=2.0.140
accessories_version=1.4.3-beta+1.21.10
curios_version=9.5.1+1.21.1
player_animation_lib_version=1.1.4+mc.1.21.1
